function f = quadrotor(in1,in2)
%QUADROTOR
%    F = QUADROTOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    21-May-2025 06:33:52

pitch_t = in1(5,:);
pitch_dot_t = in1(11,:);
roll_t = in1(4,:);
roll_dot_t = in1(10,:);
u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x_dot_t = in1(7,:);
y_dot_t = in1(8,:);
yaw_t = in1(6,:);
yaw_dot_t = in1(12,:);
z_dot_t = in1(9,:);
t2 = cos(pitch_t);
t3 = cos(roll_t);
t4 = cos(yaw_t);
t5 = sin(pitch_t);
t6 = sin(roll_t);
t7 = sin(yaw_t);
t8 = pitch_t.*2.0;
t9 = roll_t.*2.0;
t10 = yaw_dot_t.^2;
t16 = u1+u2+u3+u4;
t11 = t2.^2;
t12 = t3.^2;
t13 = sin(t8);
t14 = sin(t9);
t15 = 1.0./t11;
mt1 = [x_dot_t;y_dot_t;z_dot_t;roll_dot_t;pitch_dot_t;yaw_dot_t;(t16.*(t6.*t7+t3.*t4.*t5))./2.0;t16.*(t4.*t6-t3.*t5.*t7).*(-1.0./2.0);(t2.*t3.*t16)./2.0-9.81e+2./1.0e+2];
mt2 = [(t15.*(u2.*-1.15e+2+u4.*1.15e+2-t5.*u1.*9.2e+1+t5.*u2.*9.2e+1-t5.*u3.*9.2e+1+t5.*u4.*9.2e+1+t12.*u2.*5.5e+1-t12.*u4.*5.5e+1+pitch_dot_t.*roll_dot_t.*t13.*2.3e+1+t5.*t12.*u1.*4.4e+1-t5.*t12.*u2.*4.4e+1+t5.*t12.*u3.*4.4e+1-t5.*t12.*u4.*4.4e+1-t11.*t12.*u2.*5.5e+1+t11.*t12.*u4.*5.5e+1+pitch_dot_t.*t2.*yaw_dot_t.*1.058e+3-t3.*t6.*t10.*t11.*5.06e+2-pitch_dot_t.*t2.*t12.*yaw_dot_t.*5.06e+2+pitch_dot_t.^2.*t3.*t6.*t11.*5.06e+2-pitch_dot_t.*t2.^3.*t12.*yaw_dot_t.*5.06e+2+pitch_dot_t.*roll_dot_t.*t2.*t5.*t12.*5.06e+2-t2.*t3.*t5.*t6.*u1.*5.5e+1+t2.*t3.*t5.*t6.*u3.*5.5e+1+roll_dot_t.*t3.*t5.*t6.*t11.*yaw_dot_t.*5.06e+2))./5.52e+2];
mt3 = [((t2.*u1.*6.0e+1-t2.*u3.*6.0e+1+t14.*u1.*2.2e+1-t14.*u2.*2.2e+1+t14.*u3.*2.2e+1-t14.*u4.*2.2e+1+t2.*t12.*u1.*5.5e+1-t2.*t12.*u3.*5.5e+1+roll_dot_t.*t11.*yaw_dot_t.*5.52e+2+t5.*t10.*t11.*t12.*5.06e+2+t3.*t5.*t6.*u2.*5.5e+1-t3.*t5.*t6.*u4.*5.5e+1-roll_dot_t.*t11.*t12.*yaw_dot_t.*5.06e+2+pitch_dot_t.*roll_dot_t.*t2.*t3.*t6.*5.06e+2-pitch_dot_t.*t2.*t3.*t5.*t6.*yaw_dot_t.*5.06e+2).*(-1.0./5.52e+2))./t2];
mt4 = [(t15.*(u1.*-9.2e+1+u2.*9.2e+1-u3.*9.2e+1+u4.*9.2e+1-t5.*u2.*1.15e+2+t5.*u4.*1.15e+2+t12.*u1.*4.4e+1-t12.*u2.*4.4e+1+t12.*u3.*4.4e+1-t12.*u4.*4.4e+1+pitch_dot_t.*roll_dot_t.*t2.*4.6e+1+t5.*t12.*u2.*5.5e+1-t5.*t12.*u4.*5.5e+1+pitch_dot_t.*t13.*yaw_dot_t.*5.29e+2+pitch_dot_t.*roll_dot_t.*t2.*t12.*5.06e+2-t2.*t3.*t6.*u1.*5.5e+1+t2.*t3.*t6.*u3.*5.5e+1-t3.*t5.*t6.*t10.*t11.*5.06e+2-pitch_dot_t.*t2.*t5.*t12.*yaw_dot_t.*5.06e+2+roll_dot_t.*t3.*t6.*t11.*yaw_dot_t.*5.06e+2))./5.52e+2];
f = [mt1;mt2;mt3;mt4];
end
